# Indent lines with tabs instead of spaces.
useTabs: false

# Specify the length of line that the printer will wrap on.
printWidth: 120

# Specify the number of spaces per indentation-level.
tabWidth: 2

# Use single quotes instead of double quotes.
singleQuote: true

# Print trailing commas wherever possible.
# Valid options:
#   - "none" - no trailing commas
#   - "es5" - trailing commas where valid in ES5 (objects, arrays, etc)
#   - "all" - trailing commas wherever possible (function arguments)
trailingComma: 'none'

# Semicolons wherever necessary
semi: true

# Spacing around brackets
# true - Example: { foo: bar }.
# false - Example: {foo: bar}.
bracketSpacing: true

# If at least one property in an object requires quotes, quote all properties.
quoteProps: 'consistent'

# Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
bracketSameLine: true

# Include parentheses around a sole arrow function parameter.
arrowParens: 'avoid'
